#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.Append(
    CPPDEFINES=[
        ("SQLITE_DEFAULT_SYNCHRONOUS", 1),
        ("SQLITE_ENABLE_RBU", 1),
        ("SQLITE_USE_URI", 1),
        "SQLITE_ENABLE_JSON1",
        "SQLITE_ENABLE_FTS3",
        "SQLITE_ENABLE_FTS4",
        "SQLITE_ENABLE_FTS5",
        "SQLITE_ENABLE_RTREE",
        "SQLITE_ENABLE_DBSTAT_VTAB",
        "SQLITE_ENABLE_COLUMN_METADATA",
        "SQLITE_ENABLE_MATH_FUNCTIONS",
        ("SQLITE_DEFAULT_FOREIGN_KEYS", 1),
        ("SQLITE_TEMP_STORE", 3),
    ],
)

env.Append(CPPPATH=["#modules/sqlite/thirdparty", "#modules/sqlite"])

env["builtin_zstd"] = False

env_thirdparty = env.Clone()
env_thirdparty.disable_warnings()

module_sources = [
    "src/*.cpp",
    "src/*.c",
    "*.cpp",
]

for source_file in module_sources:
    env_thirdparty.add_source_files(env_thirdparty.modules_sources, source_file)

env_thirdparty.add_source_files(env_thirdparty.modules_sources, "#modules/sqlite/thirdparty/sqlite/sqlite3.c")
env_thirdparty.add_source_files(env_thirdparty.modules_sources, "#modules/sqlite/thirdparty/spmemvfs/spmemvfs.c")

env.modules_sources += env_thirdparty.modules_sources
