import ast, glob, numpy as np, os, sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.normpath(os.path.join(_HERE, '..', '..'))  # misc/humanoid_kusudama_rom -> repo root
# Shard outputs from the parallel Lean fit (lean/emit{0..3}.lean); override with argv[1].
SHARD_DIR = sys.argv[1] if len(sys.argv) > 1 else os.path.join(_HERE, 'lean')

FANS, GOLD = {}, {}
for f in sorted(glob.glob(os.path.join(SHARD_DIR, 'shard?.out'))):
    for line in open(f):
        line = line.rstrip('\n')
        if line.startswith('FAN|'):
            _, bone, payload = line.split('|', 2)
            twist_deg, cones = ast.literal_eval(payload)   # (twist_deg, [(sx,sz,rdeg),...])
            FANS[bone] = (float(twist_deg), [(float(a),float(b),float(c)) for a,b,c in cones])
        elif line.startswith('GOLD|'):
            _, bone, payload = line.split('|', 2)
            GOLD[bone] = [tuple(float(v) for v in t) for t in ast.literal_eval(payload)]

assert len(FANS) == 44, len(FANS)
assert len(GOLD) == 44, len(GOLD)

# 1) fan data module consumed by gen_humanoid_rom_header.py
with open(os.path.join(_HERE, 'humanoid_joint_fans.py'), 'w') as o:
    o.write('"""GENERATED by kusudama_lean/JointRom.lean via /tmp/assemble_joints.py.\n')
    o.write('Per-bone minimal anatomical Kusudama swing fans for the 44 clinical humanoid joints.\n')
    o.write('BONE_FANS[bone] = (twist_deg, [(swing_x, swing_z, radius_deg), ...]). Do not edit by hand."""\n')
    o.write('BONE_FANS = {\n')
    for b in FANS:
        tw, cones = FANS[b]
        arr = ", ".join("(%.6f, %.6f, %.6f)" % c for c in cones)
        o.write(f"    '{b}': ({tw:.6f}, [{arr}]),\n")
    o.write('}\n')

# 2) gold IK-target test header (bake frame: forward +Y, right +Z)
total = sum(len(v) for v in GOLD.values())
with open(os.path.join(_REPO, 'tests', 'scene', 'humanoid_kusudama_rom_gold.h'), 'w') as o:
    o.write('/* GENERATED by kusudama_lean/JointRom.lean (Lean+Plausible) via assemble_joints.py. */\n')
    o.write('/* Per-joint IK-target gold table: `solved` == `target` iff the target is inside the */\n')
    o.write('/* anatomical ROM (ground-truth membership; `solved` is otherwise the ideal hard */\n')
    o.write('/* projection, kept for reference). The kusudama uses a continuous/soft projection, so */\n')
    o.write('/* the test checks INVARIANTS, not exact `solved`: inside targets pass through ~unchanged, */\n')
    o.write('/* outside targets map into the (idempotent) allowed region. Canonical resource frame: */\n')
    o.write('/* forward = +Y, swing_x = +X, swing_z = +Z; the test drives solve(forward=(0,1,0), */\n')
    o.write('/* right=(1,0,0), offset=identity, target) so make_space = identity (cones used directly). */\n')
    o.write('#ifndef HUMANOID_KUSUDAMA_ROM_GOLD_H\n#define HUMANOID_KUSUDAMA_ROM_GOLD_H\n\n')
    o.write('namespace HumanoidKusudamaRomGold {\n')
    o.write('struct GoldCase { const char *bone; float target[3]; float solved[3]; };\n\n')
    o.write('static const GoldCase ROM_GOLD[] = {\n')
    for b in GOLD:
        for (tx,ty,tz,sx,sy,sz) in GOLD[b]:
            o.write('\t{ "%s", { %.6ff, %.6ff, %.6ff }, { %.6ff, %.6ff, %.6ff } },\n' % (b,tx,ty,tz,sx,sy,sz))
    o.write('};\n')
    o.write(f'static const int ROM_GOLD_COUNT = {total};\n')
    o.write('} // namespace HumanoidKusudamaRomGold\n\n#endif // HUMANOID_KUSUDAMA_ROM_GOLD_H\n')

print(f"fans: {len(FANS)} bones; gold: {len(GOLD)} bones, {total} IK-target cases")
print("sample N per bone:", {b: len(FANS[b][1]) for b in list(FANS)[:8]})
