#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_otel = env_modules.Clone()

# Include paths for GodotSQLite and its spmemvfs dependency
env_otel.Prepend(CPPPATH=["#modules/sqlite/thirdparty", "#modules/sqlite/src"])

module_obj = []

# Main module files
env_otel.add_source_files(module_obj, "*.cpp")

# Structure classes
env_otel.add_source_files(module_obj, "structures/*.cpp")

# Add test sources if tests are enabled
if env["tests"]:
    env_otel.add_source_files(env.modules_sources, "./tests/*.cpp")
    env_otel.Append(CPPDEFINES=["TESTS_ENABLED"])

env.modules_sources += module_obj
